### ISSUE TITLE
shell 스크립트로 환경변수 선언과 자동 실행하도록 구성

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/slackbot#2]
## Todo
- [x] shell 스크립트 파일 추가
- [x] 환경변수 선언부 추가 (API 토큰)
- [x] python 파일 자동 실행부 추가
